### ISSUE TITLE
[checkpoint]: one-instance architecture

### ISSUE THREAD

**Issue by sanam2405** [sanam2405/PrivacyNetwork#42]
#### Discussed in https://github.com/sanam2405/PrivacyNetwork/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **sanam2405** April 23, 2024</sup>
**SITUATION** - I have two databases (one Postgres and another MongoDB) storing data about my users (some data have intersections like email, name, age, etc.) and some data is exclusive to the two databases. 

**TASK** - Now I wish to have my data in sync with each other. Basically the common fields in both the SQL and NoSQL should be in sync real time even after performing CRUD in any of the DBs or both the DBs. 

I am thinking about implementing a _Kafka CDC(change data capture)_ but I mostly find that people are syncing _SQL-SQL_ or _NoSQ-NoSQL_ DBs using _Kafka_.

**What is a viable solution if i want the synchronisation to work in both ways?**</div>

### To-Do

- [ ] mongoDB user schema should have the postgres user id 
- [ ] seed the sql and nosql dbs with common data
- [ ] add kafka change data capture to stream the CRUD data changes across the databases

**Comment by sanam2405** [comment]
A problem however exists in this solution that if the CRUD in `loc server` is successful but the CRUD in `ts-backend server` fails, then the `loc server` CRUD is not rolled back.  **Hence, consistency is not maintained across Postgres and mongoDB in case of a successful Postgres R/W followed by a failed mongoDB R/W**

**This can be resolved by using an event driven service which continuously checks for the DB read-writes and updates the states of the DBs to the latest committed one that was consistent.**
